apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name}}-controller-pv
  labels:
    app: {{ .Release.Name }}
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.storage.kubernetesDataPath }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-controller-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi